import { useState } from "react";
import Layout from "../components/Layout";
import API from "../services/api";

function ReportsPage() {
  const [report, setReport] = useState("");
  const [loading, setLoading] = useState(false);

  const generateReport = async () => {
    setLoading(true);

    try {
      const customerData = JSON.parse(
        localStorage.getItem("customerData")
      );

      const riskAnalysis =
        localStorage.getItem("riskAnalysis");

      const recommendations =
        localStorage.getItem("recommendations");

      if (
        !customerData ||
        !riskAnalysis ||
        !recommendations
      ) {
        alert(
          "Please run Risk Analysis first."
        );

        setLoading(false);
        return;
      }

      const user = JSON.parse(
        localStorage.getItem("user")
      );

      const response = await API.post(
        "/generate-report",
        {
          customer_data: customerData,
          risk_analysis: riskAnalysis,
          recommendations: recommendations,
          email: user.email,
        }
      );

      setReport(response.data.report);

    } catch (error) {
      console.log(error);
      alert("Failed to generate report");
    }

    setLoading(false);
  };

  const downloadPDF = async () => {
    try {
      const response = await API.post(
        "/download-report",
        {
          report,
        },
        {
          responseType: "blob",
        }
      );

      const url = window.URL.createObjectURL(
        new Blob([response.data])
      );

      const link =
        document.createElement("a");

      link.href = url;

      link.setAttribute(
        "download",
        "ActuaryOS_Report.pdf"
      );

      document.body.appendChild(link);

      link.click();

      link.remove();

    } catch (error) {
      console.log(error);
      alert("Download Failed");
    }
  };

  return (
    <Layout>
      <div>
        <h1
          style={{
            fontSize: "32px",
            color: "#C084FC",
            marginBottom: "10px",
          }}
        >
          📄 AI Report Center
        </h1>

        <p
          style={{
            color: "#CBD5E1",
            marginBottom: "30px",
          }}
        >
          Generate, manage, and review actuarial reports powered by AI.
        </p>

        <div
          style={{
            display: "grid",
            gridTemplateColumns:
              "repeat(auto-fit,minmax(250px,1fr))",
            gap: "20px",
          }}
        >
          <div
            style={{
              background:
                "linear-gradient(135deg,#6D28D9,#9333EA)",
              padding: "25px",
              borderRadius: "20px",
              color: "white",
            }}
          >
            <h3>📊 Risk Assessment</h3>
            <p>
              Comprehensive risk evaluation report generated by AI.
            </p>
          </div>

          <div
            style={{
              background:
                "linear-gradient(135deg,#DB2777,#EC4899)",
              padding: "25px",
              borderRadius: "20px",
              color: "white",
            }}
          >
            <h3>👥 Customer Summary</h3>
            <p>
              AI-generated customer profile and portfolio insights.
            </p>
          </div>

          <div
            style={{
              background:
                "linear-gradient(135deg,#7C3AED,#A855F7)",
              padding: "25px",
              borderRadius: "20px",
              color: "white",
            }}
          >
            <h3>🔮 Future Projection</h3>
            <p>
              Predict future insurance risk trends and claim scenarios.
            </p>
          </div>
        </div>

        <div
          style={{
            marginTop: "30px",
            background: "#1F2937",
            padding: "25px",
            borderRadius: "20px",
            border: "1px solid #7C3AED",
          }}
        >
          <h2
            style={{
              color: "#C084FC",
              marginBottom: "20px",
            }}
          >
            AI Generated Reports
          </h2>

          <button
            onClick={generateReport}
            style={{
              marginTop: "10px",
              padding: "12px 25px",
              background: "#A855F7",
              color: "white",
              border: "none",
              borderRadius: "10px",
              cursor: "pointer",
              fontSize: "16px",
            }}
          >
            📄 Generate AI Report
          </button>

          {loading && (
            <p
              style={{
                marginTop: "20px",
                color: "#C084FC",
              }}
            >
              🤖 Generating Report...
            </p>
          )}

          {report && (
            <div
              style={{
                marginTop: "25px",
                padding: "25px",
                background: "#111827",
                borderRadius: "12px",
                border: "1px solid #7C3AED",
              }}
            >
              <h3
                style={{
                  color: "#C084FC",
                  marginBottom: "15px",
                }}
              >
                📄 AI Generated Actuarial Report
              </h3>

              <button
                onClick={downloadPDF}
                style={{
                  marginBottom: "20px",
                  padding: "12px 20px",
                  background: "#10B981",
                  color: "white",
                  border: "none",
                  borderRadius: "10px",
                  cursor: "pointer",
                }}
              >
                📄 Download PDF
              </button>

              <div
                style={{
                  whiteSpace: "pre-wrap",
                  lineHeight: "1.8",
                  color: "#E5E7EB",
                }}
              >
                {report}
              </div>
            </div>
          )}
        </div>
      </div>
    </Layout>
  );
}

export default ReportsPage;